### Sign up and get Bearer token
POST http://localhost:8085/signup
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass",
  "firstName": "test",
  "lastName": "user",
  "address": "testuser straat 1",
  "email": "userrouting@apitestuser.nl"
}

### Login and get Bearer token
POST http://localhost:8085/login
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass"
}

> {% client.global.set("bearerToken", response.body.token); %}

### Find vehicle in proximity
GET http://localhost:8085/location/search/proximity
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Breda"
}

### Book a vehicle from our previous search
POST http://localhost:8085/reservation
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

//TODO: book a vehicle from our previous search

{
  "start_time": "10-12-2025",
  "end_time": "10-12-2026",
  "vehicleId": 20,
  "userName": ""
}