### Sign up and get Bearer token
POST http://localhost:8085/signup
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass",
  "firstName": "test",
  "lastName": "user",
  "address": "testuser straat 1",
  "email": "userrouting@apitestuser.nl"
}

### Login and get Bearer token
POST http://localhost:8085/login
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass"
}

> {% client.global.set("bearerToken", response.body.token); %}

### Create vehicle for rent
POST http://localhost:8085/
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Rent out my car for a period of time
POST http://localhost:8085/
Content-Type: application/json
Authorization: Bearer {{bearerToken}}