POST http://localhost:8080/upload/cars/1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

Four images test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="photo1.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="photo2.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="photo3.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="photo4.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary--