### Sign up and get Bearer token
POST http://localhost:8085/signup
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass",
  "firstName": "test",
  "lastName": "user",
  "address": "testuser straat 1",
  "email": "userrouting@apitestuser.nl",
  "phone": "+31612345678",
  "createdAt": "2026-01-18T12:00:00"
}

### Login and get Bearer token
POST http://localhost:8085/login
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass"
}

> {%
  client.global.set("bearerToken", response.body.token);
  client.global.set("userId", response.body.userId);
%}

### Create vehicle
POST http://localhost:8085/vehicle
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "id": 100,
  "range": 600.0,
  "licensePlate": "ABC1234",
  "status": "AVAILABLE",
  "location": 1,
  "ownerId": 1,
  "photoPath": "/path/to/photo.jpg"
}

### Upload multiple images for car
POST http://localhost:8085/upload/vehicles/1
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{bearerToken}}

--WebAppBoundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

Four images test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ktor.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary

Four images test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ktor.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary

Four images test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ktor.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary

Four images test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ktor.jpg"
Content-Type: image/jpg

< ./ktor.jpg
--WebAppBoundary--
