### Sign up and get Bearer token
POST http://localhost:8085/signup
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass"
}

### Login and get Bearer token
POST http://localhost:8085/login
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass"
}

> {% client.global.set("bearerToken", response.body.token); %}

### Get all users
GET http://localhost:8085/users
Authorization: Bearer {{bearerToken}}

### Get user by ID
GET http://localhost:8085/users/1
Authorization: Bearer {{bearerToken}}

### Create user
POST http://localhost:8085/users
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "id": 1,
  "name": "John Cina",
  "role": "USER",
  "phone": "123-456-7890",
  "password": "password123",
  "email": "john@example.com",
  "driverLicenseNumber": "D1234567"
}

### Update user
PUT http://localhost:8085/users/1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "id": 1,
  "name": "Jane Doe",
  "role": "USER",
  "phone": "123-456-7890",
  "password": "password123",
  "email": "john@example.com",
  "driverLicenseNumber": "D1234567"
}

### Delete user
DELETE http://localhost:8085/users/1
Authorization: Bearer {{bearerToken}}
