### Sign up and get Bearer token
POST http://localhost:8085/signup
Content-Type: application/json

{
  "username": "userroutingapitestuser",
  "password": "userroutingtestpass",
  "firstName": "test",
  "lastName": "user",
  "address": "testuser straat 1",
  "email": "userrouting@apitestuser.nl",
  "phone": "0612345678"
}

### Login and get Bearer token
POST http://localhost:8085/login
Content-Type: application/json

{
  "username": "hdevries",
  "password": "12345"
}

> {%
  client.global.set("bearerToken", response.body.token);
  client.global.set("userId", response.body.userId);
%}

### Get all users
GET http://localhost:8085/user
Authorization: Bearer {{bearerToken}}

### Get user by ID
GET http://localhost:8085/user/{{userId}}
Authorization: Bearer {{bearerToken}}

### Create user
POST http://localhost:8085/user
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "id": 5,
  "username": "test",
  "password": "password123",
  "firstName": "Testing",
  "lastName": "Test",
  "address": "Hoogstraten 14",
  "email": "john@example.com",
  "phone": "0612345678"
}

### Update user
POST http://localhost:8085/user/5
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "id": 5,
  "username": "updatedUser",
  "password": "newPassword123",
  "firstName": "Updated",
  "lastName": "User",
  "address": "Nieuwe Straat 10",
  "email": "updatedUser@example.com",
  "phone": "0698765432"
}

### Delete user
DELETE http://localhost:8085/user/5
Authorization: Bearer {{bearerToken}}